version: '3.1'
services:
  odoo:
    image: odoo:16.0
    env_file: myenvfile.env
    depends_on:
      - postgres
    ports:
      - "8016:8069" # port mapping (custom-port:8016)
    links:
        - redis:redis
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./my_addons:/mnt/my_addons
  postgres:
    image: postgres:15
    env_file: myenvfile.env
    volumes:
      - db:/var/lib/pgsql/data/pgdata
  redis:
    container_name: redis
    image: redis:latest
    ports:
        - 6380:6379
    volumes:
        - ./config_redis/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
volumes:
  data:
  db: