{
    "name": "Test Odoo X Redis",
    "author": "IB Teguh TM",
    "website": "www.teguhteja.id",
    "description":'Test Odoo Redis',
    "version": "1.0.1",
    'category': 'Administrator',
    "depends": [],
    "data": [],
    "qweb": [],
    "license": 'LGPL-3',
    'application': True,
    'installable': True,
    'auto_install': False,
}